### PR TITLE
TD-596 - Add output with correct name for primary_connection_string

### PR DESCRIPTION
**Pull request by tom-reinders**
Changelog:
```md
### Added

- `azure/storage_account_private`: Add output `primary_connection_string` (#348) (ba78e538) (@tom-reinders)
- `azure/storage_account_public`: Add output `primary_connection_string` (#348) (ba78e538) (@tom-reinders)
```

### CODE REVIEW

**Review by bartwesselink — APPROVED** [review]
@tom-reinders kan je die daar onder deprecated maken?

**Comment by tom-reinders** [comment]
> @tom-reinders kan je die daar onder deprecated maken?

@bartwesselink 

Nope, https://github.com/hashicorp/terraform/issues/18381

I have added comments and descriptions to the deprecated outputs, but i can't make them really deprecated, will fix that if terraform fixes this before the next major version.

**Comment by bartwesselink** [comment]
@tom-reinders oké, maar kunnen wij deze niet vast klaarzetten / verwijderen in onze nieuwe major versie?

**Comment by tom-reinders** [comment]
@bartwesselink Zal ik doen.

**Comment by rquadling** [comment]
VERY VERY MUCH as a hacky solution.

Rather than the output value being JUST the value, it being a "state" of the value is sort of what is wanted. And, ideally, is what TF could be natively supporting in the future.

Downside (and the obvious one), everyone would need to learn that the value is not the value but the state of the value.

So, rather than (purely using this as an example)
```hcl
output "primary_access_connection_string" {
  description = "Deprecated in favor of primary_connection_string"
  value       = azurerm_storage_account.storage_account.primary_connection_string
  sensitive   = true
}
```
having it as
```hcl
output "primary_access_connection_string" {
  description = "Deprecated in favor of primary_connection_string"
  value       = {
    value      = azurerm_storage_account.storage_account.primary_connection_string
    deprecated = optional(bool, false)
    sensitive  = optional(bool, false)
  }
  sensitive   = true
}
```

So, then you would now have access to `output.primary_access_connection_string.value.deprecated` and so can now use tools that extract data from the state and report on deprecations (I have a validation and plan summary in play already, so adding "deprecations" to the validation as warnings, rather than errors is feasible). Also the using pre-condition checking on all output retrieved elements could block the use of deprecated elements. Harsh on the upgrades, but would work.


But all of this is horrendous for sharing. If all your work is purely in-house (and you make your own modules that get shared and grow), then ... maybe.

Really just a "what can I do that allows me to move forward" if it about purely internally managed setups.

**Comment by rquadling** [comment]
I did look at seeing if the description and annotations could be used (i.e. we put in `[deprecated<:reason>]` into the description) but this doesn't travel for `data.terraform_remote_state`). For just modules, then `terraform-config-inspect` can be used to get the descriptions from the `.terraform/modules` directory post `terraform init`. Using `terraform-config-inspect` in conjunction with `jq` can produce very readable output on what deprecations exist. Determining if you are using them is the next step there.

But all redundant as soon as Terraform has this natively.

**Pull request merged**
