### PR TITLE
Feaure/13110 improve analytics dashboard

### PR DESCRIPTION
**Pull request by ArtiomMatiom**
* Now the module need only 1 file -> the workbook template
* it can be attached to A log analytics resource or just azure monitor by using the default value
* now it generates ids automatically if needed.

### CODE REVIEW

**Review by bartwesselink — APPROVED** [review]

**Comment by tom-reinders** [comment]
Is there a reason that we are not using https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/application_insights_workbook and https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/application_insights_workbook_template ?
It looks to me that these are the same, or am I wrong?

**Comment by ArtiomMatiom** [comment]
> Is there a reason that we are not using https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/application_insights_workbook and https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/application_insights_workbook_template ? It looks to me that these are the same, or am I wrong?

good catch. I will test it and check

**Comment by bartwesselink** [comment]
@ArtiomMatiom @tom-reinders note that the change you are making is breaking, as resources will be (re-)created!

**Comment by tom-reinders** [comment]
@bartwesselink @ArtiomMatiom Sounds like something that fits right in with al the other breaking changes in the upcoming v3.0.0 version.

**Pull request merged**
